// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CLIStatus() {
  return window['go']['main']['App']['CLIStatus']();
}

export function OpenWebUI() {
  return window['go']['main']['App']['OpenWebUI']();
}

export function WebURL() {
  return window['go']['main']['App']['WebURL']();
}
