// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CLIStatus():Promise<string>;

export function OpenWebUI():Promise<string>;

export function WebURL():Promise<string>;
